## Naive Bayes Theroem for Classification


In [1]:
'''       
Let two events p(A),p(B) .


p(A/B)=p(B/A)*p(A)/p(B)


where
p(A/B)--> posterier probablity
p(B)-total prob of B  (it is also called marginal probablity which is same for all)
p(A)- prob of A
p(B/A)--> prob of B ,given A(likelihood)

Proof :::::
           p(A intersection B)=p(A/B)*p(B)       ::: conditional probability
           
           p(A instersection B)=p(B intersection A)   # commutative law
           
           p(A/B) *P(B)=P(B/A)*P(A)
           
           P(A/B)=P(B/A)*P(A)/P(B)
           
           
So :
   P(y=c|x) propotional to likelihood *prior prob
   
   we can maximaize only seeing the numerater b/c denominater always equal to all the other posterier prob.

'''

'       \nLet two events p(A),p(B) .\n\n\np(A/B)=p(B/A)*p(A)/p(B)\n\n\nwhere\np(A/B)--> posterier probablity\np(B)-total prob of B  (it is also called marginal probablity which is same for all)\np(A)- prob of A\np(B/A)--> prob of B ,given A(likelihood)\n\nProof :::::\n           p(A intersection B)=p(A/B)*p(B)       ::: conditional probability\n           \n           p(A instersection B)=p(B intersection A)   # commutative law\n           \n           p(A/B) *P(B)=P(B/A)*P(A)\n           \n           P(A/B)=P(B/A)*P(A)/P(B)\n           \n           \nSo :\n   P(y=c|x) propotional to likelihood *prior prob\n   \n   we can maximaize only seeing the numerater b/c denominater always equal to all the other posterier prob.\n\n'

##    Exmaple-  Does the patient have disease or not ?
 - A patient takes a lab test and result comes back +ve. The test  return a correct +ve in only 98% of cases in which disease is actually present and a correct -ve result in only 97% of the cases in which disease in not present .Furthermore  0.008 of the entire populations have this disease.
 
### Sol.
p(+|disease)=.98      p(-|disease)=1-.98=0.02
p(-|!disease)=.97     p(+|!disease)=1-.97=0.03
p(disease)=0.008     p(!disease)=1-0.008=.992

Naive bayes theorem. 
so  p(disease|+ve)=p(+ve|disease)*p(disease)/p(+ve)

p(+ve)=p(+ve|disease)*p(disease)+p(+ |!disease)*p(!disease)
       
      = 0.98 * 0.008 +0.03*0.992
  
p(disease| +ve) = 0.98*0.008/p(+ve)
                  
                 =20.8%
p(disease|-ve)=1-20.8=79.2%


## Naive Bayes Classifier
- it is supervised learning algorithm
- Text Classify = Exmaple  sms classify as spam or not spam 
- Email classify as inbox ,promotion,social
- Review classify as +ve,+ve,neutral. 
- p(y=1|x)=p(x|y=1)*p(y=1)/p(x)   
- p(y=0|x)=p(x|y=0)*p(y=0)/p(x)

-  compute maxargs p(yi|x)  max posterier probability
- hypothesis h=argmax((p(x/yi)*p(yi))
- p(y=1)=count all positve review/total review
        =E(i=1 to m) 1*{y(i)=1}/m
        and 
        where x=<x1,x2,x3,x4,...........x(|v|)>
        p(x|y=1)=p(x1|y)*p(x2|y=1,x1)*p(x3|y=1,x1x2)*........
 - A strong assumptions of naive bayes clssifier takes that 
   if p(x|y,x1 x2 x3.....)
   then xi depends only on output(y) not other attributes.(mean all the features is independent)
   means
   
   p(y=1|x)= p(x1|y=1)*p(y=1)/p(x) *p(x2|y=1)*p(x) *................
   
   similarly    p(y=0|x)

## Naive Bayes- Mushroom Classifcation
- Goal is to predict the class of mushrooms ,given some features of the mushrooms .We will use Naive Bayes Model for this classification.

### Load the Dataset



In [2]:
import numpy as np
import pandas as pd


In [3]:
df=pd.read_csv('mushrooms.csv')
df.head(10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [4]:
df.shape # this has 23 features and it is not numerical data it is catogorical data

(8124, 23)

## Encode the Categorial Data into Numerical Data

In [5]:
# we can convert it by iterating whole table and make a dict which map with a number of a class
# But sklearn gives this facility already in this libarary
# it has a preprocessing librery called label encoder

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split



le=LabelEncoder()
# apply tranformation on each calumns
ds=df.apply(le.fit_transform)  # it is apply only pandas dataset
ds.head()  # ds is a pandas dataframe

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [7]:
data=ds.values # convert into numpy array
print(data.shape)
print(type(data))
print(data[:5,:])
data_y=data[:,0] 
data_x=data[:,1:]

(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


## Break the Data into train and test

In [8]:
x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size=0.2)  # 80%

In [9]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [10]:
np.unique(y_train) # so there are only two type of mushroom type p and type e

array([0, 1])

In [11]:
# inverse transfromatin


## Building Our Classifier 1

In [12]:
# we have to count 1's and 0's and here is a shortcuts
a=np.array([0,0,0,1,1,0,5])
print(a==5)   # gives false except that where the number exist
np.sum(a==5) # or np.sum(a>=1)

[False False False False False False  True]


1

In [13]:
def prior_prob(y_train,label):
    
    total_example=y_train.shape[0]
    class_example=np.sum(y_train==label)
    return (class_example)/float(total_example)
    

In [14]:
#y=np.array([9,5,5,1,1,1,0,0,0,5])
#prior_prob(y,1)

In [44]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    
    x_filtered=x_train[y_train==label]
    numerator=np.sum(x_filtered[:,feature_col]==feature_val)
    denominator=np.sum(y_train==label)
    return numerator/float(denominator)

## Next Step: Compute Posterior Prob for each test example and make predictions

In [45]:
classes=np.unique(y_train)
classes

array([0, 1])

In [56]:
def predict(x_train,y_train,xtest):
    """Xtest is a single testing point ,n features"""
    
    classes=np.unique(y_train)
    n_features=x_train.shape[1]
    post_probs=[] #List of prob for all classes and given a single testing point 
    
    # Compute Posterior for each class
    for label in classes:
        
        #posterior_c=likelihood*prior
        
        likelihood=1.0
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,xtest[f],label)
            likelihood*=cond
        prior=prior_prob(y_train,label)
        post=likelihood*prior
        post_probs.append(post)
    pred=np.argmax(post_probs)
    return pred
        
        
    

In [67]:
output=predict(x_train,y_train,x_test[10]) # it mean x_test[7] is belong to class 1 mushrooms
print(output)
print(y_test[10])  # actual class 
# so it is working fine.

1
1


In [70]:
def score(x_train,y_train,x_test,y_test):
    pred=[]
    
    for i in range(x_test.shape[0]):
        pred_label=predict(x_train,y_train,x_test[i])
        pred.append(pred_label);
    pred=np.array(pred);
    accuracy=np.sum(pred==y_test)/y_test.shape[0];
    return accuracy

In [73]:
print(score(x_train,y_train,x_test,y_test)*100) # so it is approx 99.45% accuracy

99.44615384615385
