## Introduction To Netural language processing

### install NLTK
pip install nltk

In [115]:
import nltk

In [2]:
  nltk.download('stopwords')    #is use to download corpus ,we can specifie the name of corpus to download by name

[nltk_data] Downloading package stopwords to C:\Users\Gopi
[nltk_data]     Jaiswal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
# corpus -- it is large collection of text

In [4]:
from nltk.corpus import brown
brown.words()

['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', ...]

In [5]:
print(brown.categories())  # we can see the all the categories 
print(len(brown.categories()))  # there are 15 categories

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [6]:
brown?

In [7]:
data=brown.sents(categories='adventure')  # This is a syntax for check the sentences in any categories
print(data)
len(data)
print(data[1])  # we can join it



print(' '.join(data[1])) # this is the sentaces of row 1;

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]
['He', 'was', 'well', 'rid', 'of', 'her', '.']
He was well rid of her .


In [8]:
data=brown.sents(categories='fiction')
print(len(data))
print(data)

4249
[['Thirty-three'], ['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.'], ...]


In [9]:
' '.join(data[1])  # first sentence of ficition categories

'Scotty did not go back to school .'

## Bag of words pipeline
- Get the data/Corpus
- Tokenisation ,stopward Removal
- Stemming /Lemmatisation
- Building a Vocab
- Vectorization
- Classification

In [10]:
## Bag of words is a way to convert a textual data to numeric data
## Then this number give to classifier to predictions

# Tokenisation -- convert words into tokens

# words which is not meaning full is called stopword removal.Exmaple
#  i am running . so here am is need not to collect
# so we can remove word like preposition ,determinance a,an ,the etc.


### Stemming/lemmatisation -- convert diffenent form of the verb to different base verb.


## after tokenisation and stopward removal and stemming there is left  only list of unique words.( building a vocab) 


# vectorisation-- we make a list with all 0 of size list of unique words and at every time we increses the freq of words at that index.

# it does not matter the oreder mean oreder is not important .


## Tokenisations and stopword removal

In [11]:
# coversion is like 
# documents->list of sentences--> list of vocabulary
document="""It was pleasant day. The weather was cool and slower. I went to market to buy some fruits.  """  # it is a documents


sentence=" Send to all 50 documents related to chapter 1,2,3 at gopi.jais0607@gmail.com "


In [12]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [13]:
sents=sent_tokenize(document)
print(sents)
print(len(sents))

['It was pleasant day.', 'The weather was cool and slower.', 'I went to market to buy some fruits.']
3


In [14]:
word=word_tokenize(sents[0])

In [15]:
word

['It', 'was', 'pleasant', 'day', '.']

In [16]:
word_tokenize(sentence) # it split into word based on space by split we can split it on the basis of ,

['Send',
 'to',
 'all',
 '50',
 'documents',
 'related',
 'to',
 'chapter',
 '1,2,3',
 'at',
 'gopi.jais0607',
 '@',
 'gmail.com']

## Stopword

In [17]:
from nltk.corpus import stopwords 

In [18]:
sw=set(stopwords.words('english'))

In [19]:
print(sw)
len(sw)

{"you'd", 'ain', "weren't", 'have', 'during', 'out', 'again', 'each', 'own', 'now', 'shan', 'was', 'were', 'further', "you've", 'yourselves', 'needn', 'how', 'had', 'if', 'him', 'my', 'has', 'whom', 'off', "haven't", 'wouldn', 'those', 'shouldn', 'am', "should've", 'it', 'most', 'yours', 'herself', 've', "isn't", 's', 'them', 'when', 'o', 'do', 'y', "needn't", 'hers', 'until', 'all', "she's", 'very', 'below', 'both', 'didn', 'too', 'so', 'up', "mightn't", 'before', "you're", 'his', 'with', 'did', 'me', 'd', 'ourselves', 'yourself', 'wasn', 'than', 'in', "shouldn't", 'where', 'through', 'there', 'by', 'don', 'or', 'being', 'be', 'under', 'll', 'i', 'then', 'for', 'no', 'over', 'just', 'against', 'mustn', 'doing', 'you', 'the', "wouldn't", 'an', 'can', 'should', 'been', 'won', 'mightn', 'from', 'between', 'once', 'while', 'not', 'as', 'our', 'what', 're', "didn't", "that'll", 'themselves', 'these', 'after', 'are', 'same', 'they', 'and', 'few', 't', 'haven', "won't", 'couldn', 'myself', '

179

In [20]:
def remove_stopwords(text,stopwords):
    useful_words= [w for w in text if w not in stopwords]
    return useful_words

In [21]:
text="i am not bothered  about her very much"
text=list(text.split(" "))
usefulwords=remove_stopwords(text,sw) # it remove 'not' also which can sentiment the meaning of useful words

In [22]:
print(usefulwords)


['bothered', '', 'much']


##  Tokenising using Regular Expression

In [23]:

# use Regex pal website to undersands regular expession
sentence=" Send to all 50 documents related to chapter 1,2,3 at gopi.jais0607@gmail.com "
remove_stopwords(list(sentence.split(",")),sw)  # we can see that it is not removing the numeric data
# also if we tokenize the
print(word_tokenize(sentence))  # it also showing the numberic data which me be infinite 

['Send', 'to', 'all', '50', 'documents', 'related', 'to', 'chapter', '1,2,3', 'at', 'gopi.jais0607', '@', 'gmail.com']


In [24]:
# we can use regular expression to remove this type of text


from nltk.tokenize import RegexpTokenizer

In [25]:
tokenizer=RegexpTokenizer('[a-zA-Z@.]+')  # + select the words as token
usefulwords = tokenizer.tokenize(sentence)


In [26]:
print(usefulwords)


['Send', 'to', 'all', 'documents', 'related', 'to', 'chapter', 'at', 'gopi.jais', '@gmail.com']


# Stemming 
- Process that transforms particular words(verbs,plurals)int their radical form
- Preserve the sementics of the sentence without increasing the nunber of unique tokens
- Example -umps,jumping,jumped,jump ====>> jump

In [27]:
text=""""Foxes love to make jumps.
The quick brown fox was seen jumping over the lovely dog from a 6 ft feet high wall"""

In [28]:
# nltk provides three type of stemmer 
# Snowball Stemmer,Portar,Lancaster Stemmer
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [29]:
ps=PorterStemmer() # object 
ps.stem('jumping')

'jump'

In [30]:
ps.stem('jumps')

'jump'

In [31]:
ps.stem('lovely')

'love'

In [32]:
ps.stem('loving')

'love'

In [33]:
# NOTE: Every stemmer works on differente set of rules so it can gives different results


In [34]:
# SnowballStemmer  It is multilanguage stemmer so we want to specifie the language also

ss=SnowballStemmer('english')

In [35]:
ss.stem('lovely')

'love'

In [36]:
ss.stem('jumping')

'jump'

In [37]:
# nltk.download('wordnet') download wordnet

In [38]:
## lemmatizations it is oraganize by WordNet
from nltk.stem import WordNetLemmatizer
wn=WordNetLemmatizer()
wn.lemmatize("lovely")

'lovely'

## Building a Vocab & Vectorization

In [39]:
# sample Corpus -Contains 4 Documents,each documents can Move 1 or more sentences

corpus=[
      'Indian cricket team will wins world Cup,says Capt.Virat Kohli.World cup will be held at Sri Lanka',
       'We will win next Lok Sabha Elections,says confident Indian PM',
      'The nobel laurate won the hearts of the people.',
    'The movie Raazi is an exciting Indian Spy thriller based upon a real story.', 
]

# 1 sports ,2 plolitics 3 economy 4 movie

# so we will convert each doc as a one feature vector

# so can use dict to store the vocab

# but here we are using sk learn for doing this.

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
cv=CountVectorizer() # creating a object

vectorized_corpus=cv.fit_transform(corpus)

In [42]:
vectorized_corpus
len(vectorized_corpus.shape)

2

In [43]:
#vectorized_corpus?  here we can see that ex-(0,6)  1 mean in the 0 sentence first word getting 6 index in the dict with freq 1 


In [44]:
vectorized_corpus=vectorized_corpus.toarray()


In [45]:

# see the first documents
print(vectorized_corpus[0])
len(vectorized_corpus[0])

[0 1 0 1 1 0 1 2 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0
 2 0 1 0 2]


42

In [46]:
print(cv.vocabulary_ ) # we can see the word in vocab

{'indian': 12, 'cricket': 6, 'team': 31, 'will': 37, 'wins': 39, 'world': 41, 'cup': 7, 'says': 27, 'capt': 4, 'virat': 35, 'kohli': 14, 'be': 3, 'held': 11, 'at': 1, 'sri': 29, 'lanka': 15, 'we': 36, 'win': 38, 'next': 19, 'lok': 17, 'sabha': 26, 'elections': 8, 'confident': 5, 'pm': 23, 'the': 32, 'nobel': 20, 'laurate': 16, 'won': 40, 'hearts': 10, 'of': 21, 'people': 22, 'movie': 18, 'raazi': 24, 'is': 13, 'an': 0, 'exciting': 9, 'spy': 28, 'thriller': 33, 'based': 2, 'upon': 34, 'real': 25, 'story': 30}


In [47]:
len(cv.vocabulary_.keys())

42

In [48]:
# Reverse mapping 
numbers=vectorized_corpus[2]
s=cv.inverse_transform(numbers)
print(numbers)
print(s)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 3 0 0 0 0
 0 0 0 1 0]
[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
      dtype='<U9')]


## Vectorization with Stopword Removal

In [52]:
 # we can see that it take a tokenizer so we can give our tokenizer

In [53]:
cv=CountVectorizer() # object of vectorizer 

In [54]:
print(cv) #Here we can see that it is taking a tokenizer functions so we can give our tokenizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [56]:
def myTokenizer(document):
    words=tokenizer.tokenize(document.lower());  # so that indian and Indian should treated as same 
    words=remove_stopwords(words,sw)
    return words
    
    
myTokenizer("this is my function")    # so it is giving only function as a usefull words

['function']

In [62]:
myTokenizer(sentence) # only few words out of all documents

['send', 'documents', 'related', 'chapter', 'gopi.jais', '@gmail.com']

In [63]:
# pass our tokenizer in the function

cv=CountVectorizer(tokenizer=myTokenizer)

In [74]:
vectorized_corpus=cv.fit_transform(corpus).toarray()
print(vectorized_corpus)
print(len(vectorized_corpus[0]))  #so it is reduce 42 to 32
#vectorized_corpus

[[0 1 0 1 2 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1]
 [0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0]]
32


In [75]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.virat', 'cricket', 'cup', 'held', 'indian', 'kohli.world',
        'lanka', 'says', 'sri', 'team', 'wins', 'world'], dtype='<U11'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U11'),
 array(['hearts', 'laurate', 'nobel', 'people.'], dtype='<U11'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U11')]

In [80]:
# for test data 
# we will call fit_transform for training data and only transform for test data otherwise it will overwite the vocabulary

test_coupus=[
    "Indian","cricket","rocks!"
]


test=cv.transform(test_coupus)  # if i am using fit_transform it will overwrite the vocabulary

In [81]:
cv.vocabulary_  # it is not overwrite 

{'indian': 9,
 'cricket': 3,
 'team': 26,
 'wins': 30,
 'world': 31,
 'cup': 4,
 'says': 22,
 'capt.virat': 1,
 'kohli.world': 10,
 'held': 8,
 'sri': 24,
 'lanka': 11,
 'win': 29,
 'next': 15,
 'lok': 13,
 'sabha': 21,
 'elections': 5,
 'confident': 2,
 'pm': 18,
 'nobel': 16,
 'laurate': 12,
 'hearts': 7,
 'people.': 17,
 'movie': 14,
 'raazi': 19,
 'exciting': 6,
 'spy': 23,
 'thriller': 27,
 'based': 0,
 'upon': 28,
 'real': 20,
 'story.': 25}

In [82]:
# lets overwirte the vocabualry
cv.fit_transform(test_coupus)
cv.vocabulary_   # now ir has been modified 

{'indian': 1, 'cricket': 0, 'rocks': 2}

In [83]:
# Note :we will use fit_trasform for training data and transform for test data 

# More Ways to create Features


- Unigram ->  every words as a feature ex- this is good movie so this ,is, good movie may be a feature
- Bigrams-> every conjuctive pair of words as a  feature
- Trigrams
- n-grams
- TF-IDF Normalisation

In [85]:
sent_1=["this is good movie"]
sent_2=["This is not good movie"]

In [86]:
cv=CountVectorizer()
docs=[sent_1[0],sent_2[0]]
cv.fit_transform(docs).toarray(0)
# here it is difficult to capture negation so it is difficult to give correct out
# Because here is confusion it may predict that both or good


array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [87]:
cv.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'not': 3}

In [91]:
# Now take an example lets
sent_1=["this is good movie"]
sent_2=["this is good movie but actor is not present"]
sent_3=["this is not good movie"]
# here sent_1 and sent_2 both are + review but both containg words good,movie,not so it will take it as positive review which is cofunsion
# it due to we are captureing the not good feature together .so we will use Bigrams

# in Bigrams it will increase the the size of the vector 
# but it also has some advantage 
cv=CountVectorizer(ngram_range=(3,3))
cv.fit_transform(docs).toarray()

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]], dtype=int64)

In [92]:
cv.vocabulary_

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

In [93]:
# we can use  trigram replace (ngram_range=(3,3))




# TF-IDF Noramlisation  (Term Frequency and Inverse Document Frequency)
- Avoid features that occur very other because they contain less information
- Information decreases as the number of occurences increses across different type of documents
- So we define another term -term-document-frequency which associates a weight with every 

In [109]:
sent_1="this is good movies"
sent_2="this was good movie"
sent_3="this is not good movie"
corpus=[sent_1,sent_2,sent_3]

In [110]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [111]:
tfidf=TfidfVectorizer()
vc=tfidf.fit_transform(corpus).toarray()
print(vc)

[[0.39148397 0.50410689 0.         0.66283998 0.         0.39148397
  0.        ]
 [0.39148397 0.         0.50410689 0.         0.         0.39148397
  0.66283998]
 [0.34957775 0.45014501 0.45014501 0.         0.59188659 0.34957775
  0.        ]]


In [113]:
tfidf.vocabulary_  #here at index was has weight height in   2 document and  in rest it has 0

{'this': 5, 'is': 1, 'good': 0, 'movies': 3, 'was': 6, 'movie': 2, 'not': 4}

In [114]:
# here tf(t,d)--> an term occur in d's document
# idf(t,d)-->log N/(1+count(t,d))-->log (N/count(t,d))
# where N is total documents
# in exmaple 
# exmaple for is tfidf feature is 1*log(3/1)  
# so we can feed tfidf for any machine learning classifer